version: "2.4"
services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: "${ENV}"
    env_file:
      - base.env
      - "${ENV}.env"
    volumes:
      - ./app:/app
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster

  redis:
    image: redis:7.0